CREATE TABLE TRAIN (
    UUID CHAR(36) NOT NULL PRIMARY KEY,
    TRAIN_NO INT,
    TRAIN_KIND VARCHAR(255),
    CREATED_DATE DATETIME,
    CREATED_BY VARCHAR(255),
    LAST_UPDATED_DATE DATETIME,
    LAST_UPDATED_BY VARCHAR(255)
);

CREATE TABLE TRAIN_STOP (
    UUID CHAR(36) NOT NULL PRIMARY KEY,
    TRAIN_UUID CHAR(36),
    SEQ INT,
    NAME VARCHAR(255),
    TIME TIME,
    DELETE_FLAG VARCHAR(255),
    CREATED_DATE DATETIME,
    CREATED_BY VARCHAR(255),
    LAST_UPDATED_DATE DATETIME,
    LAST_UPDATED_BY VARCHAR(255),
    CONSTRAINT FK_TRAIN_STOP_TRAIN FOREIGN KEY (TRAIN_UUID) REFERENCES TRAIN(UUID)
);

CREATE TABLE TRAIN_TICKET (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TICKET_NO VARCHAR(255) NOT NULL,
    TRAIN_UUID VARCHAR(255) NOT NULL,
    FROM_STOP VARCHAR(255) NOT NULL,
    TO_STOP VARCHAR(255) NOT NULL,
    PRICE DECIMAL(19, 2) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    LAST_UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR(255)
);

CREATE TABLE TRAIN_SEAT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TICKET_UUID CHAR(36) NOT NULL,
    TRAIN_UUID CHAR(36) NOT NULL,
    BOOK_UUID CHAR(36) NOT NULL,
    TAKE_DATE DATE,
    SEAT_NO VARCHAR(255),
    BOOKED CHAR(2),
    ACTIVE_FLAG CHAR(2),
    CREATED_DATE DATETIME,
    CREATED_BY VARCHAR(255),
    LAST_UPDATED_DATE DATETIME,
    LAST_UPDATED_BY VARCHAR(255)
);

CREATE TABLE TICKET_BOOKING (
    UUID CHAR(36) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TRAIN_UUID CHAR(36) NOT NULL,
    TICKET_UUID CHAR(36) NOT NULL,
    ACTIVE_FLAG CHAR(2),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    LAST_UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `EVENT_LOG` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UUID` char(36) NOT NULL,
  `USER_ID` varchar(32) NOT NULL,
  `EVENT_CLASS_NAME` varchar(255) NOT NULL,
  `OCCURED_AT` datetime NOT NULL,
  `TARGET_ID` char(36) NOT NULL,
  `BODY` longtext NOT NULL,
  `SEND_QUEUE_STATUS` varchar(30) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `event_idempotent_log` (
  `EVENT_TYPE` varchar(190) NOT NULL,
  `UNIQUE_KEY` varchar(64) NOT NULL,
  `TARGET_ID` char(36),
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`event_type`,`unique_key`),
  KEY `idx_type_key` (`event_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

